# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - npm set registry http://npm.colorfy.me:4873/
          - npm adduser <<!
            $NPM_USER
            $NPM_PASS
            $NPM_MAIL
            !
          - npx semantic-release --no-ci
